### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I'm requesting to be added as a maintainer so I can build v1.3.1 with python 3.8.  Airflow requires a `lazy-object-proxy<1.4.0`

**Comment by xylar** [comment]
@jakirkham, given that the purpose of this build is just to add me as a maintainer, do you think it would be safe not to bump the build number?  Seems kind of pointless...

**Comment by jakirkham** [comment]
Yeah it's not needed. Was just trying to save a round of iteration where we remove it 🙂

**Comment by xylar** [comment]
@jakirkham, thanks very much!

**Pull request merged**
